/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package covid.pkg19application;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 * This class is a log in form
 * @author Enxhi Tabaku
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    protected static String email;
    
    public LogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldEmail = new javax.swing.JTextField();
        jButtonSignIn = new javax.swing.JButton();
        jButtonSignUp = new javax.swing.JButton();
        jPasswordFieldLogIn = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Covid-19 App");
        setResizable(false);
        setSize(new java.awt.Dimension(377, 398));

        jPanel1.setMinimumSize(new java.awt.Dimension(377, 398));
        jPanel1.setPreferredSize(new java.awt.Dimension(377, 398));
        jPanel1.setLayout(null);

        jTextFieldEmail.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTextFieldEmail.setToolTipText("Enter your email address");
        jTextFieldEmail.setBorder(null);
        jTextFieldEmail.setName(""); // NOI18N
        jTextFieldEmail.setOpaque(false);
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(30, 100, 320, 20);

        jButtonSignIn.setBorderPainted(false);
        jButtonSignIn.setContentAreaFilled(false);
        jButtonSignIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignInActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSignIn);
        jButtonSignIn.setBounds(260, 230, 90, 30);

        jButtonSignUp.setBorderPainted(false);
        jButtonSignUp.setContentAreaFilled(false);
        jButtonSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignUpActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSignUp);
        jButtonSignUp.setBounds(170, 350, 90, 30);

        jPasswordFieldLogIn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jPasswordFieldLogIn.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordFieldLogIn.setToolTipText("Enter your password");
        jPasswordFieldLogIn.setBorder(null);
        jPasswordFieldLogIn.setOpaque(false);
        jPanel1.add(jPasswordFieldLogIn);
        jPasswordFieldLogIn.setBounds(30, 170, 320, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\CovidMENU\\Log_In.png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 380, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignUpActionPerformed
        
        SignUp menu=new SignUp();
        
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_jButtonSignUpActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jButtonSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignInActionPerformed
        String password=String.valueOf(jPasswordFieldLogIn.getPassword());
        
        if(UserClass.verifyLogInDB(jTextFieldEmail.getText(),password) ){
            
            email=jTextFieldEmail.getText();//store the email temporary
            
            MainMenu menu=new MainMenu();
            
            menu.setVisible(true);
            menu.setLocationRelativeTo(null);
            this.setVisible(false);
            this.dispose();
        }else
            JOptionPane.showMessageDialog(null,"Invalid User Credentials","Covid-19",JOptionPane.ERROR_MESSAGE);
        
        /*
        if( UserClass.verifyLogIn( readUsers("C:\\Users\\user\\Desktop\\Covid19Users.txt"), jTextFieldEmail.getText(), password) )
        {
            email=jTextFieldEmail.getText();
            
            MainMenu menu=new MainMenu();
            
            menu.setVisible(true);
            menu.setLocationRelativeTo(null);
            this.setVisible(false);
            this.dispose();
        }
        */
    }//GEN-LAST:event_jButtonSignInActionPerformed

 
    /**
     *This method will open, close the file  and read from the it 
     * @param pathName the path of the respective file
     * @return ArrayList fileUsers
     */
    /*
    protected static ArrayList<UserClass> readUsers(String pathName){
 
        ArrayList<UserClass> fileUsers = new ArrayList<>();
        
        try{
            File file=new File(pathName);
            Scanner read=new Scanner(file);
 
            while(read.hasNextLine()){
                String data = read.nextLine();
                fileUsers.add(new UserClass(data));//store the users to the List 
            }//End of while
            read.close();   
        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(null,"An error occurred.","ERROR",JOptionPane.ERROR_MESSAGE); //File not Found    
            e.printStackTrace();
        }
        catch(IndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null,"An error occurred.","ERROR INDEX OUT OF BOUNDURY",JOptionPane.ERROR_MESSAGE);    
            e.printStackTrace();
        }

        return fileUsers;//return a List of the items in the file
    }
    */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton jButtonSignIn;
    private javax.swing.JButton jButtonSignUp;
    private static javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldLogIn;
    protected static javax.swing.JTextField jTextFieldEmail;
    // End of variables declaration//GEN-END:variables
}
