/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package covid.pkg19application;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * This class is a main menu form
 * @author Enxhi Tabaku
 */
public class MainMenu extends javax.swing.JFrame {
    //Declaring variables to be overwritten
    protected static String potentialZip=" ";
    protected static int potentialCases=11,sum=11,areaNoCases=11;
    
    protected static final HashMap<String,String>MAPID=(HashMap<String,String>) UserClass.storeDBemailAndID();
    protected static String id=MAPID.get( LogIn.email );
    
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonPatientReport = new javax.swing.JButton();
        jButtonNoticeBoard = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Covid-19 App");
        setMinimumSize(new java.awt.Dimension(604, 260));
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(604, 260));
        jPanel1.setLayout(null);

        jButtonPatientReport.setToolTipText("Check your symptoms report");
        jButtonPatientReport.setBorder(null);
        jButtonPatientReport.setContentAreaFilled(false);
        jButtonPatientReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPatientReport.setPreferredSize(new java.awt.Dimension(75, 30));
        jButtonPatientReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPatientReportActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPatientReport);
        jButtonPatientReport.setBounds(25, 70, 155, 146);

        jButtonNoticeBoard.setToolTipText("Check what's happening");
        jButtonNoticeBoard.setBorder(null);
        jButtonNoticeBoard.setContentAreaFilled(false);
        jButtonNoticeBoard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNoticeBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNoticeBoardActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNoticeBoard);
        jButtonNoticeBoard.setBounds(225, 70, 150, 146);

        jButton3.setToolTipText("Add Your Symptoms");
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(420, 70, 160, 150);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\CovidMENU\\Main_Menu.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 604, 260);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPatientReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPatientReportActionPerformed
        PatientReport menu= new PatientReport();
        
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonPatientReportActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        if(AddSymp.submitClicked)
            JOptionPane.showMessageDialog(null,"You entered your symptoms once for today \n Come back tomorrow", "CAUTION !",JOptionPane.PLAIN_MESSAGE);
        else{
        AddSymp menu=new AddSymp();
        
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        this.setVisible(false);
        this.dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonNoticeBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNoticeBoardActionPerformed
        //ArrayList<NoticeBoardClass>list=NoticeBoard.readNotice("C:\\Users\\user\\Desktop\\Notice_Board.txt");
        //if(list!=null)    
        //{
            
        //NoticeBoard.openFileAndTakeActions("C:\\Users\\user\\Desktop\\Notice_Board.txt");
       
        NoticeBoard.NoticeToDB();
        sumOfCases();
        potentialCasesAndZIP();
        infectedAreaNoUsers();
        
        NoticeBoard menu=new NoticeBoard();

        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        this.setVisible(false);
        this.dispose();
        
        //else{
        //    JOptionPane.showMessageDialog(null,"No Data Entered Yet", "CAUTION !",JOptionPane.PLAIN_MESSAGE);
        //}
    }//GEN-LAST:event_jButtonNoticeBoardActionPerformed

    //ITS OK
     protected static void sumOfCases(){
        try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javaproject?zeroDateTimeBehavior=convertToNull","root","");
            PreparedStatement state=con.prepareStatement("SELECT SUM(Cases) AS sumcases FROM noticeboard");
            ResultSet rs=state.executeQuery();
            if(rs.next()){
                sum=rs.getInt("sumcases");
                //Debbug System.out.println("SUM OF CASES : "+sum);
            }
        } catch (SQLException ex) {
            Logger.getLogger(NoticeBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
     
     //Its OK
     protected static void potentialCasesAndZIP(){
        try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javaproject?zeroDateTimeBehavior=convertToNull","root","");
            PreparedStatement state=con.prepareStatement("SELECT * FROM `noticeboard` \n" +
                                                         "ORDER BY Cases DESC\n" +
                                                         "LIMIT 1"); //Retrieve only the first row of the table in desc order a.k.a the zip code with highest no of cases
            ResultSet rs=state.executeQuery();
            
            if(rs.next()){
                 potentialZip=rs.getString("Zip");
                 potentialCases=rs.getInt("Cases");
                //Debug System.out.println(potentialZip+" "+potentialCases);
            }//End of IF
        
        } catch (SQLException ex) {
            Logger.getLogger(NoticeBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
     //Its Ok
     protected static void infectedAreaNoUsers(){
         HashMap<String,String>tempMap=(HashMap<String,String>) UserClass.storeDBidAndZIP();
         String userZip=tempMap.get(id);
         System.out.println("ID: "+id);
         System.out.println("User ZIP: "+userZip);
          try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javaproject?zeroDateTimeBehavior=convertToNull","root","");
            PreparedStatement state4=con.prepareStatement("SELECT * FROM `noticeboard` " ); 
            ResultSet rs=state4.executeQuery();
            
            //this wont loop through all the records in the databae FIX IT . NOTE: FIXED ! .next() point one before the last record. 
            while(rs.next()){
                String zip=rs.getString("Zip");
                System.out.println(zip+" = "+userZip+" ?");
                if(zip.equals(userZip)){//match the logged in user to find its area infected no
                    areaNoCases=rs.getInt("Cases");
                    System.out.println("Area No Cases: "+areaNoCases);
                }//End of Nested IF
                
            }//End of IF
        
        } catch (SQLException ex) {
            Logger.getLogger(NoticeBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonNoticeBoard;
    private javax.swing.JButton jButtonPatientReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
